apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: position-trajectory-controller
  labels:
    app: starling

spec:
  selector:
    matchLabels:
      name: position-trajectory-controller

  template:
    metadata:
      labels:
        name: position-trajectory-controller

    spec:
      nodeSelector:
        # starling.dev/vehicle-class: rotary
        starling.dev/type: vehicle

      tolerations:
      - key: "starling.dev/type"
        operator: "Equal"
        value: "vehicle"
        effect: "NoSchedule"

      hostNetwork: true
      shareProcessNamespace: true

      containers:
      - name: position-trajectory-controller
        image: uobflightlabstarling/position-trajectory-controller
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /etc/starling/vehicle.config
          name: vehicleconfig
          readOnly: true

      volumes:
      - name: vehicleconfig
        hostPath:
          path: /etc/starling/vehicle.config
          type: File
---

# Central montior
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sync-monitor
spec:
  selector:
    matchLabels:
      app:  sync-monitor
  template:
    metadata:
      labels:
        app: sync-monitor
    spec:
      hostNetwork: true
      shareProcessNamespace: true
      nodeSelector:
        name: master
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: sync-monitor
        image: uobflightlabstarling/position-trajectory-controller
        imagePullPolicy: Always
        env:
          - name: RUN_MONITOR
            value: "true"
      - name: starling-allocator
        image: uobflightlabstarling/starling-allocator:latest
        imagePullPolicy: Always
      - name: starling-ui
        image: mickeyli789/starling-ui-dashly:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      - name: rosbridge-suite
        image: uobflightlabstarling/rosbridge-suite:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9090
