kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: starling-cluster
nodes:
- role: control-plane
  labels:
    name: master
  extraPortMappings:
  # Gazebo
  - containerPort: 8080
    hostPort: 8080
  # UI
  - containerPort: 3000
    hostPort: 3000
  # Rosbridge Suite
  - containerPort: 9090
    hostPort: 9090
  - containerPort: 7681
    hostPort: 7681
  # Dashboard
  - containerPort: 31771
    hostPort: 31771
  - containerPort: 11345
    hostPort: 11345
    protocol: UDP
  # Mavlink out
  - containerPort: 4560
    hostPort: 4560
